import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useState, useRef } from 'react'


export default function Home() {

const [page, setPage] = useState(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"])  
const [cargando, setCargando] = useState(true)

const prueba = useRef(null)


const callback = (entradas) => {
  if(entradas[0].isIntersecting){
    prueba.current.src = "/10.jpg"
    setCargando(false)
  }
 
}

useEffect(()=>{

 const observador = new IntersectionObserver(callback, {
  rootMargin: "0px 0px 50px 0px",
  threshold: 0.1
 }) 

 observador.observe(prueba.current)

},[prueba])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <button
            onClick={()=>{
              add()
            }}
           >Add</button>
         </div>

      
      
      
       <div className={styles.center}>
        <Image
         src={'/1.jpg'}
         className={styles.logo}
         alt="Next.js Logo"
         width={500}
         height={500}
         priority
        />
     </div>
          
     <div className={styles.center}>
        <Image
         src={'/1.jpg'}
         className={styles.logo}
         alt="Next.js Logo"
         width={500}
         height={500}
         priority
        />
     </div>
          
     <div className={styles.center}>
        <Image
         src={'/1.jpg'}
         className={styles.logo}
         alt="Next.js Logo"
         width={500}
         height={500}
         priority
        />
     </div>
          
     <div className={styles.center}>
        <Image
         src={'/1.jpg'}
         className={styles.logo}
         alt="Next.js Logo"
         width={500}
         height={500}
         priority
        />
     </div>
     <div>
     {cargando ? <h2>Cargando...</h2> : <h2>Cargada</h2>}
     </div>
     
     <div className={styles.center}>
         <Image
         ref={prueba}
         className={styles.logo}
         alt="Next.js Logo"
         width={500}
         height={500}
         priority
        />
     </div>

      
      </main>
    </>
  )
}
