import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useState, useRef } from 'react'
import Imageload from './components/Imageload'


export default function Home() {

const [page, setPage] = useState(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16"])  
const [cargando, setCargando] = useState(true)


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
         </div>

    <div>
          <Image src="/assets/1.jpg" className={styles.logo} alt="prueba" width={500} height={500}/> 
          
     </div>
     <div>
          <Image src="/assets/2.jpg" className={styles.logo} alt="prueba" width={500} height={500}/> 
          
     </div> 
      <div>
          <Image src="/assets/3.jpg" className={styles.logo} alt="prueba" width={500} height={500}/> 
     </div>
     <div>
        {page.map ( (src, i) => 
          <div className={styles.logo} key={i}>
             <Imageload src={src}/>
          </div>
          )}
     </div>
      

      
      </main>
    </>
  )
  }